{% set name = "tzinfo-data" %}
{% set version = "1.2022.5" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: ba141b76d18ec7c93bc633df896cf441914d77d5a40987d35f436400bfa258f0

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-tzinfo >=1.0.0

test:
  commands:
    - gem list -i {{ name }} -v {{ version }}

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: TZInfo::Data contains data from the IANA Time Zone database packaged as Ruby modules for use with TZInfo.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tzinfo/{{ name }}

extra:
  recipe-maintainers:
    - bgruening
    - sodre
