travis:
  secure:
    BINSTAR_TOKEN: c4Iy6pMc1ktRoAJhOR4K9MBq7mHDShsl2qQi1o86ti1vKugjIwMQl7B9mmjWX93FLMFnqQXb9j98UbmNnKyIBx9L8QZXFIF864FVP+kRxDblV+FLB5HsO2dHFobNymAwjY8LkwzYi7IoEqGq/qemZk7DK1EghtFbQ5MQQICZVvsYpoQT8O+SeRzRSRNWXR9sydkM8x8/L7IJXjT1h7DsxGLlsIn6P1Hr9nlRmStkhOVC/aWkQzlM9PPXSZ9O9dMW+i+mXpiG+8wCDa/LPGnt3NVulR3AgepDmeXYwHa+/XnE20baQBiotwF+n7fpoMN+pQ6TO4U4NF7kCfpJqoaqR9MkBGblmr6gIiymQiQeGcYQRvPcfhWXjJgeM1mzeuRPw6gqjqd3HyKQyhdOYrNj+QFiW8FfdCsqMmMVXdQk7S6r9twCM6y1jB8rVbZWbf5QihM7owJ2ytbnnZY9zm3kPi64mwF3Yng/EtjdBQvw20ydNanaBQ+XCqbKCvE6xq0yzDXA8egq8Ri7WadtebajSVZm4sqgTCPBXHhl59+YS46+BOF32VvqPIyhna51oyei79x1yxfhSi/MnyjFF8Zn1rxJtXDBiW3FKL+rLWt1nNBIB998dIbkezhy9wT+m7s/oUvd1HldtwYS7zDmRVKYqUyRTbQUYoJs4DuDNI4Gkzs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
